Bump hacking to 3.0.1
This bumps hacking to 3.0.1 to resolve the following conflict causing
failure during installation.

ERROR: Cannot install hacking and pyflakes>=2.1.1 because these package
versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyflakes>=2.1.1
    flake8 2.6.2 depends on pyflakes!=1.2.0, !=1.2.1, !=1.2.2, <1.3 and
    >=0.8.1
    The user requested pyflakes>=2.1.1
    flake8 2.6.1 depends on pyflakes!=1.2.0, !=1.2.1, !=1.2.2, <1.3 and
    >=0.8.1
    The user requested pyflakes>=2.1.1
    flake8 2.6.0 depends on pyflakes!=1.2.0, !=1.2.1, !=1.2.2, <1.3 and
    >=0.8.1

Change-Id: Ie378f9bcbe6096b362cec81ab00c04e952667ea8